# Generated by Django 5.2.7 on 2026-02-04 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('estoques', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logentrada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logretirada',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retiradas_destino', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='logretirada',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiradas', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='logretirada',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiradas', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='logretirada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together={('empresa', 'produto')},
        ),
    ]
