# Generated by Django 5.2.7 on 2026-02-04 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('EM_CRIACAO', 'Em Criação'), ('EM_PROCESSO_AUTORIZACAO', 'Em processo de autorização'), ('AUTORIZADA', 'Autorizada'), ('UNIDA', 'Unida'), ('EM_PROCESSO_CONSOLIDACAO', 'Em processo de consolidação'), ('CONSOLIDADA', 'Consolidada'), ('EM_PROCESSO_COMPRA', 'Em Processo de Compra'), ('EM_ENTREGA', 'Em Rota de Entrega'), ('RECEBIDA', 'Itens Recebidos')], default='EM_CRIACAO', max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogAlteracaoLista',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_antiga', models.PositiveIntegerField()),
                ('quantidade_nova', models.PositiveIntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemListaCompra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_desejada', models.PositiveIntegerField(default=0)),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
