# Generated by Django 5.2.7 on 2026-02-04 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('empresas', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listacompra',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listacompra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_compra', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='listacompra',
            name='listas_unidas',
            field=models.ManyToManyField(blank=True, related_name='lista_principal', to='compras.listacompra'),
        ),
        migrations.AddField(
            model_name='itemlistacompra',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.listacompra'),
        ),
        migrations.AddField(
            model_name='logalteracaolista',
            name='alterado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logalteracaolista',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes', to='compras.listacompra'),
        ),
        migrations.AddField(
            model_name='logalteracaolista',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AlterUniqueTogether(
            name='listacompra',
            unique_together={('empresa', 'numero')},
        ),
    ]
